# Generated by Django 4.1 on 2022-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_questions_q_image_questions_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
