# Generated by Django 4.1 on 2022-08-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_questions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachers',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
