# Generated by Django 4.1 on 2022-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_questions_author_id_teachers_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
