# Generated by Django 4.1 on 2022-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='q_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
