# Generated by Django 4.1 on 2022-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_answer_q_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
