# Generated by Django 4.1 on 2022-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_answer_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='difficulty_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('sum_diff', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='posted_by',
        ),
    ]
