# Generated by Django 4.1 on 2022-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_reports_answer_q_id_alter_difficulty_tbl_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='q_id',
            field=models.CharField(max_length=10),
        ),
    ]
