# Generated by Django 4.1 on 2022-08-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_answer_grade_alter_answer_q_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.CharField(default=1, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='q_id',
            field=models.CharField(max_length=1000),
        ),
    ]
