# Generated by Django 4.1 on 2022-08-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_user_id_alter_answer_grade_alter_answer_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
