# Generated by Django 4.1 on 2022-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_questions_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
