# Generated by Django 4.1 on 2022-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_questions_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_content',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
