# Generated by Django 4.1 on 2022-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_answer_question_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='imagesExams/')),
                ('checked', models.BooleanField(default=False)),
                ('grade', models.CharField(default=0, max_length=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_content',
        ),
        migrations.AddField(
            model_name='questions',
            name='diffi',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='author_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
