# Generated by Django 4.1 on 2022-08-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_exam_answers_remove_answer_question_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam_answers',
        ),
    ]
